### ISSUE TITLE
Flavor compiling problem

### ISSUE THREAD

**Issue by paolo-caroni** [allu77/aMuleRemote#2]
Honestly I'm new on gradle, I have problem with compiling or maybe it's a bug?

`/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/helpers/ec/ECHelper.java:26: error: cannot find symbol
import com.iukonline.amule.android.amuleremote.Flavor;
                                                                           ^`
`  symbol:   class Flavor
  location: package com.iukonline.amule.android.amuleremote
/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/helpers/UpdateChecker.java:24: error: cannot find symbol
import com.iukonline.amule.android.amuleremote.Flavor;
                                                                           ^`
`  symbol:   class Flavor
  location: package com.iukonline.amule.android.amuleremote
/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/helpers/ec/ECHelper.java:26: error: cannot find symbol
import com.iukonline.amule.android.amuleremote.Flavor;
                                                                           ^`
`  symbol:   class Flavor
  location: package com.iukonline.amule.android.amuleremote
/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/helpers/UpdateChecker.java:24: error: cannot find symbol
import com.iukonline.amule.android.amuleremote.Flavor;
                                                                           ^`
`  symbol:   class Flavor
  location: package com.iukonline.amule.android.amuleremote
/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/AmuleRemoteApplication.java:307: error: cannot find symbol
        if (Flavor.ACRA_ENABLED) ACRA.init(this);
            ^`
`  symbol:   variable Flavor
  location: class AmuleRemoteApplication
/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/AmuleRemoteApplication.java:307: error: illegal start of type
        if (Flavor.ACRA_ENABLED) ACRA.init(this);
           ^`
`/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/AmuleRemoteApplication.java:315: error: cannot find symbol
            if (! Flavor.UPDATE_CHECKER_CHECK_BUILD) {
                  ^`
`  symbol:   variable Flavor
  location: class AmuleRemoteApplication
/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/helpers/ec/ECHelper.java:491: error: cannot find symbol
            if (Flavor.ACRA_ENABLED) ACRA.getErrorReporter().putCustomData("ServerVersion", mECClient.getServerVersion());
                ^`
`  symbol:   variable Flavor
  location: class ECHelper
/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/helpers/ec/ECHelper.java:491: error: illegal start of type
            if (Flavor.ACRA_ENABLED) ACRA.getErrorReporter().putCustomData("ServerVersion", mECClient.getServerVersion());
               ^`
`/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/helpers/UpdateChecker.java:40: error: cannot find symbol
    private static final String AC_UPDATE_URL = Flavor.UPDATE_CHECKER_URL_PREFIX;
                                                                            ^`
`  symbol:   variable Flavor
  location: class UpdateChecker
/home/paolo/git/aMuleRemote/app/src/main/java/com/iukonline/amule/android/amuleremote/helpers/UpdateChecker.java:41: error: cannot find symbol
    private static final long AC_UPDATE_INTERVAL = Flavor.UPDATE_CHECKER_INTERVAL;
                                                                                   ^`
`  symbol:   variable Flavor
  location: class UpdateChecker
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
9 errors
:app:compileTargetDebugJavaWithJavac FAILED`

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileTargetDebugJavaWithJavac'.

```

**Comment by allu77** [comment]
I'm not a gradle expert too. The gradle script was buily by Android Studio and also the com.iukonline.amule.android.amuleremote.Flavor was something I built for using the Build Variants feature from Android Studio (https://developer.android.com/studio/build/build-variants.html)a, in order to differentiate between development, snaptshot and prod releases.

So... first question: are you using android studio?

**Comment by paolo-caroni** [comment]
Hi allu77.
Honestly not, I don't use Android Studio. Probably when I have time i start to study it.
anyway Android Studio use Gradle to compile, so it must be possible to use Gradle directly.

I noticed that there are three flavors on build.gradle (dev, snapshot, target) but only two Flavor.java code.
I added a fake "aMuleRemote / app / src / target / java / com / iukonline / amule / Android / amuleremote / Flavor.java" for the target flavor and the error is gone.

It still must point out that the minsdk must be upgraded to 11.
PartFileActivity.java:402: Call requires API level 11 (current min is 8).

You can probably close this issue.
Cheers,
Paolo
